#!/usr/bin/with-contenv bash

umask 022

#variables set in Dockerfile

cd "${APP_ROOT}/${APPDIRNAME}" || exit

cmd="s6-setuidgid abc $APP_COMP $APP_COMP_OPTS $APP_EXEC $APP_OPTS"
echo "Executing: [$cmd]"
exec $cmd
